server:
  port: ${PORT:8093}

spring:
  application:
    name: BOOKING-SERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/hotel_bookings}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:true}

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890}
  expiration: 3600000
