server:
  port: ${PORT:8093}

spring:
  application:
    name: BOOKING-SERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://hotel_db_user:bpR7axsHo7abot4r@hotelmanagement.yzu70xs.mongodb.net/hotel_bookings?retryWrites=true&w=majority}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:true}

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890}
  expiration: 3600000
