server:
  port: 8095

spring:
  application:
    name: REVIEW-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/hotel_reviews
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
