server:
  port: 8095

spring:
  application:
    name: REVIEW-SERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://hotel_db_user:bpR7axsHo7abot4r@hotelmanagement.yzu70xs.mongodb.net/hotel_reviews?retryWrites=true&w=majority}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
