server:
  port: 8097

spring:
  application:
    name: ANALYTICS-SERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://hotel_db_user:bpR7axsHo7abot4r@hotelmanagement.yzu70xs.mongodb.net/hotel_analytics?retryWrites=true&w=majority}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
