server:
  port: ${PORT:8091}

spring:
  application:
    name: USER-SERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://hotel_db_user:bpR7axsHo7abot4r@hotelmanagement.yzu70xs.mongodb.net/hotel_users?retryWrites=true&w=majority}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:myUltraSecretKeyForJWTGeneration12345}
  expiration: 3600000 # 1 hour

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:true}
